/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */
import { cloudDatabase } from '@kit.CloudFoundationKit';

class Post extends cloudDatabase.DatabaseObject {
  id: number;
  userId: string = "";
  content: string = "";
  name: string;
  profilePicture: string;
  insertDate: Date;
  likes: string = "[]";
  likeCount: number = 0;

  naturalbase_ClassName(): string {
    return 'Post';
  }
}

export { Post };