export { loginPage } from './src/main/ets/view/loginPage'

export { regPage } from './src/main/ets/view/regPage'

export { createUserSetInfoPage } from './src/main/ets/view/createUserSetInfoPage'

export { updateUserInfoPage } from './src/main/ets/view/UpdateUserInfoPage'

export { bindPhoneNumberPage } from './src/main/ets/view/bindPhoneNumberPage'

export { bindEmailPage } from './src/main/ets/view/bindEmailPage'


